# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obj_scorer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(664, 540))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraWidget = CameraWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraWidget.sizePolicy().hasHeightForWidth())
        self.cameraWidget.setSizePolicy(sizePolicy)
        self.cameraWidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.cameraWidget.setObjectName("cameraWidget")
        self.verticalLayout.addWidget(self.cameraWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(323, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 90))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        self.playButton.setEnabled(False)
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setIconSize(QtCore.QSize(32, 32))
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        self.stopButton.setEnabled(False)
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(32, 32))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.sourceLabel = QtWidgets.QLabel(self.centralwidget)
        self.sourceLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sourceLabel.setObjectName("sourceLabel")
        self.verticalLayout_2.addWidget(self.sourceLabel)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.destLabel = QtWidgets.QLabel(self.centralwidget)
        self.destLabel.setObjectName("destLabel")
        self.verticalLayout_2.addWidget(self.destLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.trialLabel = QtWidgets.QLabel(self.centralwidget)
        self.trialLabel.setObjectName("trialLabel")
        self.verticalLayout_3.addWidget(self.trialLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.commentsButton = QtWidgets.QPushButton(self.centralwidget)
        self.commentsButton.setObjectName("commentsButton")
        self.verticalLayout_4.addWidget(self.commentsButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.videoInSlider = QtWidgets.QSlider(self.centralwidget)
        self.videoInSlider.setEnabled(False)
        self.videoInSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoInSlider.setObjectName("videoInSlider")
        self.verticalLayout.addWidget(self.videoInSlider)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displayTsCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.displayTsCheckBox.setObjectName("displayTsCheckBox")
        self.horizontalLayout_3.addWidget(self.displayTsCheckBox)
        self.rotateComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.rotateComboBox.setObjectName("rotateComboBox")
        self.horizontalLayout_3.addWidget(self.rotateComboBox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.mirroredButton = QtWidgets.QCheckBox(self.centralwidget)
        self.mirroredButton.setObjectName("mirroredButton")
        self.horizontalLayout_3.addWidget(self.mirroredButton)
        self.rawVideoCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.rawVideoCheckBox.setEnabled(False)
        self.rawVideoCheckBox.setObjectName("rawVideoCheckBox")
        self.horizontalLayout_3.addWidget(self.rawVideoCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.scaleComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.scaleComboBox.setEnabled(False)
        self.scaleComboBox.setCurrentText("")
        self.scaleComboBox.setObjectName("scaleComboBox")
        self.horizontalLayout_4.addWidget(self.scaleComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Camera = QtWidgets.QAction(MainWindow)
        self.actionOpen_Camera.setCheckable(False)
        self.actionOpen_Camera.setObjectName("actionOpen_Camera")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionBanana = QtWidgets.QAction(MainWindow)
        self.actionBanana.setObjectName("actionBanana")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave_to = QtWidgets.QAction(MainWindow)
        self.actionSave_to.setObjectName("actionSave_to")
        self.actionOpen_Live_Session = QtWidgets.QAction(MainWindow)
        self.actionOpen_Live_Session.setObjectName("actionOpen_Live_Session")
        self.actionOpen_Video_Session = QtWidgets.QAction(MainWindow)
        self.actionOpen_Video_Session.setObjectName("actionOpen_Video_Session")
        self.menuFile.addAction(self.actionOpen_Live_Session)
        self.menuFile.addAction(self.actionOpen_Video_Session)
        self.menuFile.addAction(self.actionOpen_Camera)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cameraWidget.setToolTip(_translate("MainWindow", "Video Viewer for Behavioral Tracking"))
        self.cameraWidget.setWhatsThis(_translate("MainWindow", "A Video Viewer for OpenCV based behavioral trackingusing PyQt."))
        self.groupBox.setTitle(_translate("MainWindow", "Play Controls"))
        self.playButton.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.pauseButton.setShortcut(_translate("MainWindow", "Ctrl+Space, Meta+Space"))
        self.stopButton.setShortcut(_translate("MainWindow", "Ctrl+Down, Meta+Down"))
        self.label.setText(_translate("MainWindow", "Playing from:"))
        self.sourceLabel.setText(_translate("MainWindow", "NO SOURCE"))
        self.label_2.setText(_translate("MainWindow", "Writing to:"))
        self.destLabel.setText(_translate("MainWindow", "NO DEST"))
        self.label_5.setText(_translate("MainWindow", "Trial No."))
        self.trialLabel.setText(_translate("MainWindow", "0"))
        self.commentsButton.setText(_translate("MainWindow", "Insert Comments"))
        self.displayTsCheckBox.setText(_translate("MainWindow", "Display timestamps"))
        self.label_4.setText(_translate("MainWindow", "Rotate (degrees)"))
        self.mirroredButton.setText(_translate("MainWindow", "Mirrored"))
        self.rawVideoCheckBox.setText(_translate("MainWindow", "Save raw video"))
        self.label_3.setText(_translate("MainWindow", "Image scale"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Camera.setText(_translate("MainWindow", "Open Camera..."))
        self.actionOpen_Camera.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File..."))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionBanana.setText(_translate("MainWindow", "Banana"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionSave_to.setText(_translate("MainWindow", "Save to..."))
        self.actionSave_to.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_Live_Session.setText(_translate("MainWindow", "Open Live Session..."))
        self.actionOpen_Video_Session.setText(_translate("MainWindow", "Open Video Session..."))

from scorer_gui.obj_scorer_model import CameraWidget
import scorer_gui.obj_rc
import scorer_gui.play_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

