# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obj_scorer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 621)
        MainWindow.setMinimumSize(QtCore.QSize(664, 540))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraWidget = CameraWidget(self.centralwidget)
        self.cameraWidget.setObjectName("cameraWidget")
        self.verticalLayout.addWidget(self.cameraWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(323, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 90))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        self.playButton.setEnabled(False)
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setIconSize(QtCore.QSize(32, 32))
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        self.stopButton.setEnabled(False)
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(32, 32))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.sourceLabel = QtWidgets.QLabel(self.centralwidget)
        self.sourceLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sourceLabel.setObjectName("sourceLabel")
        self.verticalLayout_2.addWidget(self.sourceLabel)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.destLabel = QtWidgets.QLabel(self.centralwidget)
        self.destLabel.setObjectName("destLabel")
        self.verticalLayout_2.addWidget(self.destLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.videoInSlider = QtWidgets.QSlider(self.centralwidget)
        self.videoInSlider.setEnabled(False)
        self.videoInSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoInSlider.setObjectName("videoInSlider")
        self.verticalLayout.addWidget(self.videoInSlider)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displayTsCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.displayTsCheckBox.setObjectName("displayTsCheckBox")
        self.horizontalLayout_3.addWidget(self.displayTsCheckBox)
        self.mirroredButton = QtWidgets.QCheckBox(self.centralwidget)
        self.mirroredButton.setObjectName("mirroredButton")
        self.horizontalLayout_3.addWidget(self.mirroredButton)
        self.rawVideoCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.rawVideoCheckBox.setEnabled(False)
        self.rawVideoCheckBox.setObjectName("rawVideoCheckBox")
        self.horizontalLayout_3.addWidget(self.rawVideoCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Camera = QtWidgets.QAction(MainWindow)
        self.actionOpen_Camera.setCheckable(False)
        self.actionOpen_Camera.setObjectName("actionOpen_Camera")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionBanana = QtWidgets.QAction(MainWindow)
        self.actionBanana.setObjectName("actionBanana")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave_to = QtWidgets.QAction(MainWindow)
        self.actionSave_to.setObjectName("actionSave_to")
        self.menuFile.addAction(self.actionOpen_Camera)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave_to)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cameraWidget.setToolTip(_translate("MainWindow", "Video Viewer for Behavioral Tracking"))
        self.cameraWidget.setWhatsThis(_translate("MainWindow", "A Video Viewer for OpenCV based behavioral trackingusing PyQt."))
        self.groupBox.setTitle(_translate("MainWindow", "Play Controls"))
        self.playButton.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.pauseButton.setShortcut(_translate("MainWindow", "Ctrl+Space, Meta+Space"))
        self.stopButton.setShortcut(_translate("MainWindow", "Ctrl+Down, Meta+Down"))
        self.label.setText(_translate("MainWindow", "Playing from:"))
        self.sourceLabel.setText(_translate("MainWindow", "NO SOURCE"))
        self.label_2.setText(_translate("MainWindow", "Writing to:"))
        self.destLabel.setText(_translate("MainWindow", "NO DEST"))
        self.displayTsCheckBox.setText(_translate("MainWindow", "Display timestamps"))
        self.mirroredButton.setText(_translate("MainWindow", "Mirrored"))
        self.rawVideoCheckBox.setText(_translate("MainWindow", "Save raw video"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Camera.setText(_translate("MainWindow", "Open Camera..."))
        self.actionOpen_Camera.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File..."))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionBanana.setText(_translate("MainWindow", "Banana"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionSave_to.setText(_translate("MainWindow", "Save to..."))
        self.actionSave_to.setShortcut(_translate("MainWindow", "Ctrl+S"))

from scorer_gui.obj_scorer_model import CameraWidget
import play_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

