# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trial_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrialDialog(object):
    def setupUi(self, TrialDialog):
        TrialDialog.setObjectName("TrialDialog")
        TrialDialog.resize(538, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(TrialDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(TrialDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sessionLineEdit = QtWidgets.QLineEdit(TrialDialog)
        self.sessionLineEdit.setObjectName("sessionLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sessionLineEdit)
        self.label_3 = QtWidgets.QLabel(TrialDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.runLineEdit = QtWidgets.QLineEdit(TrialDialog)
        self.runLineEdit.setObjectName("runLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.runLineEdit)
        self.label_2 = QtWidgets.QLabel(TrialDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.trialLineEdit = QtWidgets.QLineEdit(TrialDialog)
        self.trialLineEdit.setObjectName("trialLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.trialLineEdit)
        self.label_4 = QtWidgets.QLabel(TrialDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.subjectLineEdit = QtWidgets.QLineEdit(TrialDialog)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.label_5 = QtWidgets.QLabel(TrialDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.location1ComboBox = QtWidgets.QComboBox(TrialDialog)
        self.location1ComboBox.setObjectName("location1ComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.location1ComboBox)
        self.label_6 = QtWidgets.QLabel(TrialDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.location2ComboBox = QtWidgets.QComboBox(TrialDialog)
        self.location2ComboBox.setObjectName("location2ComboBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.location2ComboBox)
        self.label_7 = QtWidgets.QLabel(TrialDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.objectComboBox = QtWidgets.QComboBox(TrialDialog)
        self.objectComboBox.setObjectName("objectComboBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.objectComboBox)
        self.label_8 = QtWidgets.QLabel(TrialDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.subjectTrialLineEdit = QtWidgets.QLineEdit(TrialDialog)
        self.subjectTrialLineEdit.setEnabled(True)
        self.subjectTrialLineEdit.setObjectName("subjectTrialLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.subjectTrialLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.objectLabel = QtWidgets.QLabel(TrialDialog)
        self.objectLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.objectLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.objectLabel.setText("")
        self.objectLabel.setObjectName("objectLabel")
        self.horizontalLayout_2.addWidget(self.objectLabel)
        self.objLocLabel = QtWidgets.QLabel(TrialDialog)
        self.objLocLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.objLocLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.objLocLabel.setText("")
        self.objLocLabel.setObjectName("objLocLabel")
        self.horizontalLayout_2.addWidget(self.objLocLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(TrialDialog)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addTrialButton = QtWidgets.QPushButton(TrialDialog)
        self.addTrialButton.setObjectName("addTrialButton")
        self.horizontalLayout.addWidget(self.addTrialButton)
        self.skipTrialButton = QtWidgets.QPushButton(TrialDialog)
        self.skipTrialButton.setObjectName("skipTrialButton")
        self.horizontalLayout.addWidget(self.skipTrialButton)
        self.stdButtons = QtWidgets.QDialogButtonBox(TrialDialog)
        self.stdButtons.setOrientation(QtCore.Qt.Horizontal)
        self.stdButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.stdButtons.setObjectName("stdButtons")
        self.horizontalLayout.addWidget(self.stdButtons)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TrialDialog)
        self.stdButtons.accepted.connect(TrialDialog.accept)
        self.stdButtons.rejected.connect(TrialDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TrialDialog)

    def retranslateUi(self, TrialDialog):
        _translate = QtCore.QCoreApplication.translate
        TrialDialog.setWindowTitle(_translate("TrialDialog", "Dialog"))
        self.label.setText(_translate("TrialDialog", "Session"))
        self.label_3.setText(_translate("TrialDialog", "Scheme nr."))
        self.label_2.setText(_translate("TrialDialog", "Sequence nr"))
        self.label_4.setText(_translate("TrialDialog", "Subject"))
        self.label_5.setText(_translate("TrialDialog", "Location 1"))
        self.label_6.setText(_translate("TrialDialog", "Location 2"))
        self.label_7.setText(_translate("TrialDialog", "Object"))
        self.label_8.setText(_translate("TrialDialog", "Trial"))
        self.addTrialButton.setText(_translate("TrialDialog", "Add Trial"))
        self.skipTrialButton.setText(_translate("TrialDialog", "Skip Trial"))

import score_behavior.obj_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrialDialog = QtWidgets.QDialog()
    ui = Ui_TrialDialog()
    ui.setupUi(TrialDialog)
    TrialDialog.show()
    sys.exit(app.exec_())

