# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracking_controller/tracker_control_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrackerControl(object):
    def setupUi(self, TrackerControl):
        TrackerControl.setObjectName("TrackerControl")
        TrackerControl.resize(336, 220)
        TrackerControl.setMinimumSize(QtCore.QSize(336, 0))
        TrackerControl.setMaximumSize(QtCore.QSize(351, 220))
        self.verticalLayout = QtWidgets.QVBoxLayout(TrackerControl)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(TrackerControl)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 36))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backgroundButton = QtWidgets.QPushButton(self.widget)
        self.backgroundButton.setObjectName("backgroundButton")
        self.horizontalLayout.addWidget(self.backgroundButton)
        self.initButton = QtWidgets.QPushButton(self.widget)
        self.initButton.setObjectName("initButton")
        self.horizontalLayout.addWidget(self.initButton)
        self.resetButton = QtWidgets.QPushButton(self.widget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.showThreshCheckBox = QtWidgets.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showThreshCheckBox.setFont(font)
        self.showThreshCheckBox.setObjectName("showThreshCheckBox")
        self.horizontalLayout_2.addWidget(self.showThreshCheckBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 52))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.thresholdSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.thresholdSpinBox.setObjectName("thresholdSpinBox")
        self.verticalLayout_3.addWidget(self.thresholdSpinBox)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 52))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.speedSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.verticalLayout_4.addWidget(self.speedSpinBox)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stateLabel = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stateLabel.setFont(font)
        self.stateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateLabel.setObjectName("stateLabel")
        self.verticalLayout_5.addWidget(self.stateLabel)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.animalsLabel = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.animalsLabel.setFont(font)
        self.animalsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.animalsLabel.setObjectName("animalsLabel")
        self.verticalLayout_6.addWidget(self.animalsLabel)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(TrackerControl)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.retranslateUi(TrackerControl)
        QtCore.QMetaObject.connectSlotsByName(TrackerControl)

    def retranslateUi(self, TrackerControl):
        _translate = QtCore.QCoreApplication.translate
        TrackerControl.setWindowTitle(_translate("TrackerControl", "Form"))
        self.groupBox.setTitle(_translate("TrackerControl", "Tracker controls"))
        self.backgroundButton.setText(_translate("TrackerControl", "Set BG"))
        self.initButton.setText(_translate("TrackerControl", "Init Anim."))
        self.resetButton.setText(_translate("TrackerControl", "Reset Anim."))
        self.showThreshCheckBox.setText(_translate("TrackerControl", "Show Thresh."))
        self.groupBox_2.setTitle(_translate("TrackerControl", "Threshold"))
        self.groupBox_3.setTitle(_translate("TrackerControl", "Speed thresh. flips"))
        self.groupBox_4.setTitle(_translate("TrackerControl", "Tracking State"))
        self.stateLabel.setText(_translate("TrackerControl", "Inactive"))
        self.groupBox_5.setTitle(_translate("TrackerControl", "Animals"))
        self.animalsLabel.setText(_translate("TrackerControl", "0/1"))

